version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: farmer-marketplace-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: farmer-marketplace
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build: ./backend
    container_name: farmer-marketplace-api
    restart: always
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/farmer-marketplace?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      OPENWEATHER_API_KEY: your-openweather-api-key
      AI_SERVICE_URL: http://ai-service:8000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  ai-service:
    build: ./ai-service
    container_name: farmer-marketplace-ai
    restart: always
    environment:
      PORT: 8000
      ENVIRONMENT: development
      OPENWEATHER_API_KEY: your-openweather-api-key
      BACKEND_API_URL: http://backend:5000
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app

  frontend:
    build: ./frontend
    container_name: farmer-marketplace-frontend
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_AI_SERVICE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - ai-service

  nginx:
    image: nginx:alpine
    container_name: farmer-marketplace-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - ai-service

volumes:
  mongodb_data:

networks:
  default:
    name: farmer-marketplace-network
